export const employeeColumns = [
    {
        field: 'employeeId', headerName: 'ID', width: 130,
        cellClassName: "name-column--cell",
    },
    { field: 'employeeMat', headerName: 'EMPLOYEE MAT', width: 170 },
    { field: 'department', headerName: 'DEPARTMENT', width: 170 },
    { field: 'supervisor', headerName: 'SUPERVISOR', width: 170 },
    { field: 'firstname', headerName: 'FIRST NAME', width: 170 },
    { field: 'lastname', headerName: 'LAST NAME', width: 170 },
    { field: 'birthdate', headerName: 'DATE-OF-BIRTH', width: 170 },
    { field: 'birthplace', headerName: 'PLACE-OF-BIRTH', width: 150 },
    { field: 'gender', headerName: 'GENDER', width: 100 },
    { field: 'status', headerName: 'STATUS', width: 100 },
    { field: 'email', headerName: 'EMAIL', width: 170 },
    { field: 'address', headerName: 'ADDRESS', width: 170},
    { field: 'phone', headerName: 'PHONE', width: 170 },
    { field: 'function', headerName: 'FUNCTION', width: 170},
    { field: 'hiringdate', headerName: 'HIRING-DATE', width: 170},
    { field: 'seniority', headerName: 'SENIORITY', width: 170},
    { field: 'salary', headerName: 'SALARY', width: 170},
    { field: 'whatsappnumber', headerName: 'WHATSAPP-NUMBER', width: 170},
    { field: 'facebooklink', headerName: 'FACEBOOK-LINK', width: 170},
    { field: 'resourcecontact', headerName: 'RESOUCE-CONTACT', width: 170},
    { field: 'resourcename', headerName: 'RESOURCE-NAME', width: 170},
    { field: 'isChiefOfDepartment', headerName: 'IS-CHIEF-OF-DEPARTMENT', width: 170},
    { field: 'typeofemployee', headerName: 'TYPE-OF-EMPLOYEE', width: 170}
]